//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCartV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineItem
    {
        public int OrderID { get; set; }
        public int LineNumber { get; set; }
        public int ProductID { get; set; }
        public int Quantity { get; set; }
        public decimal ExtendedPrice { get; set; }
    }
}
